version: "2.1"
services:
  app:
    container_name: app2
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo2
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
